create custom links that show up on the profile page
vgalilei/venturecat pull request #122
Opened 2021-12-07 04:37 UTC by rileydanejohnston

**Note: this PR relies on an adjustment to env files. I will put this in Slack.

features:
- profile page displays a link with the user's unique formUrl which can be clicked and copied
- slight refactoring - using react's Link instead of anchor element
- removing the signedup page because it's the same as the profile page except less unique to the user.

future stuff
- the profile page will display the FULL link. ex _https:://www.site.com_. I left it this way so the user has the option to copy by highlighting the text. We could also trim the link to only show _www.site.com_ if we wanted.

- [ ] My code is covered by unit tests 
- [ x] This PR is less than [300 lines of code](https://www.atlassian.com/blog/git/written-unwritten-guide-pull-requests)
- [ x] My code [smells good](https://en.wikipedia.org/wiki/Code_smell) 
- [ x] I have tested my PR locally and proven it works. 
- [ x] There is [no copy-paste](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)

2021-12-07 05:54 UTC, McCambley requested changes
Nice! A few changes needed. I'll message you in slack with the github action changes.

2021-12-07 05:54 UTC, McCambley commented on frontend/src/components/app/App.js
> +            formPath={user && `form/${user.formUrl}`}
Awesome, this looks good, but drill this down to the other profile component in the investor feed above (line 88). When there are no startups, this profile will (with some style changes) will appear there with the same url. Right now that Url reads as undefined.

2021-12-07 05:54 UTC, McCambley commented on frontend/src/components/profile/Profile.js
> +      <LinkUrl to={`/${formPath}`}>{`${REACT_APP_FRONTEND_URL}/${formPath}`}</LinkUrl>
It's beautiful ✨

2021-12-07 05:54 UTC, McCambley commented on frontend/src/components/profile/Profile.js
> +  const { REACT_APP_FRONTEND_URL } = process.env;
I'm not sure that this is really needed in our github action runs, but just in case, update this in the ci yml file. I'll send you a code snippet in slack regarding this. 

I think `.env.prod` should include `REACT_APP_FRONTEND_URL=http://localhost:5000` too. I'll message you about this as well.

2021-12-07 05:54 UTC, McCambley commented on frontend/src/components/app/App.js
> -        <ProtectedRoute exact path="/signedup" isAuthorized={loggedIn}>
👋

2021-12-07 23:21 UTC, rileydanejohnston commented on frontend/src/components/app/App.js
> +            formPath={user && `form/${user.formUrl}`}
Solved this more or less. I just used the user component they already passed rather than pass another prop with the same info.

2021-12-09 05:12 UTC, McCambley approved these changes
Looks awesome Riley.

2021-12-09 05:12 UTC, McCambley commented on frontend/src/components/investor-feed/InvestorFeed.js
> +      formPath={user.user && `form/${user.user.formUrl}`}
Perf ✨

2021-12-09 05:12 UTC, McCambley approved these changes

2021-12-09 05:14 UTC, merged