Startup Form responsive
vgalilei/venturecat pull request #148
Opened 2021-12-20 15:31 UTC by mentalcaries

# Describe your changes 

At this PR I worked on responsive behaviour for the startup form.
Since some styles could not have been overwritten(eg. `order`), I created modified versions of the existing components for this page

# I follow best practices 

- [ ] My code is covered by unit tests 
- [ ] This PR is less than [300 lines of code](https://www.atlassian.com/blog/git/written-unwritten-guide-pull-requests)
- [ ] My code [smells good](https://en.wikipedia.org/wiki/Code_smell) 
- [ ] I have tested my PR locally and proven it works. 
- [ ] There is [no copy-paste](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)

2021-12-20 15:53 UTC, mariawright05 commented
Looks great to me - you'll need to resolve the conflicts above, and I will approve!

2021-12-20 16:12 UTC, mariawright05 approved these changes

2021-12-21 00:23 UTC, McCambley requested changes
Looks great! Just a few things:
1) `LargeCaption` should be center aligned in smaller windows
2) The padding looks like it's set correctly, but items (inputs and buttons) are overflowing their container making the padding on the right hand side look a little smaller than the left. Set the L and R margins of the parent of the form to 0 and it looks like that takes it away

I think that's it.

2021-12-21 00:54 UTC, McCambley approved these changes
It's beauuuuuutiful

2021-12-21 00:55 UTC, merged