App secret
vgalilei/venturecat pull request #153
Opened 2021-12-21 03:13 UTC by mentalcaries

# Describe your changes 

At this PR I created the secret key for the app.
Updates to environment variables to follow in Slack channel

# I follow best practices 

- [ ] My code is covered by unit tests 
- [ ] This PR is less than [300 lines of code](https://www.atlassian.com/blog/git/written-unwritten-guide-pull-requests)
- [ ] My code [smells good](https://en.wikipedia.org/wiki/Code_smell) 
- [ ] I have tested my PR locally and proven it works. 
- [ ] There is [no copy-paste](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)

2021-12-21 03:35 UTC, McCambley approved these changes
One comment below, but looks good! Approved!

2021-12-21 03:35 UTC, McCambley commented on backend/app.js
> +const { DOTCOT_SECRET, MONGODB_URI, FRONTEND_URL } = process.env;
Something like "SESSION_SECRET" might be a little more descriptive, as these are all sort of "DOTCOT_SECRETS", but that's not a big deal at all. This looks good, thanks for hiding the things!

2021-12-21 03:39 UTC, McCambley requested changes
Forgot to add in the previous review, and realized I could resubmit another review. This variable should be added to the `.yml` files to be used in ci/cd stuff (testing and deployment). Vlad should also add this secret to the repositories secrets.

2021-12-21 11:19 UTC, mentalcaries commented on backend/app.js
> +const { DOTCOT_SECRET, MONGODB_URI, FRONTEND_URL } = process.env;
I like it

2021-12-22 02:20 UTC, McCambley approved these changes
Looks good to me. Once @vgalilei adds the secret to the settings in this repository, we should start seeing tests pass.

2021-12-22 02:20 UTC, McCambley commented on .github/workflows/CI-only.yml
> +      DOTCOT_SECRET: ${{secrets.DOCTCOT_SECRET}}
👍

2021-12-22 15:59 UTC, vgalilei commented
We have broken tests in the main branch. I think tests will not pass even if I add this to the env. 
I rather advise putting some fake keys directly to the CI configuration than adding to secrets. Because it is not secret while we run tests

2021-12-22 22:50 UTC, merged