Investor feed
vgalilei/venturecat pull request #94
Opened 2021-11-23 10:10 UTC by mentalcaries

# Describe your changes 

At this PR I removed the unused code and started the responsive design.
This work is ongoing, but this preliminary PR is to allow for early visualisation of how these changes affect the landing page components.

# I follow best practices 

- [ ] My code is covered by unit tests 
- [ ] This PR is less than [300 lines of code](https://www.atlassian.com/blog/git/written-unwritten-guide-pull-requests)
- [ ] My code [smells good](https://en.wikipedia.org/wiki/Code_smell) 
- [ ] I have tested my PR locally and proven it works. 
- [ ] There is [no copy-paste](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)

2021-11-25 20:10 UTC, McCambley commented
@mentalcaries I sent you a message in slack, but currently there are merge conflict text pieces getting in the way of review. These aren't merge conflicts themselves, but rather the text used to resolve merge conflicts. See the screenshots to see what they look like in both Github and VSCode. Choose the right code to keep, get rid of the markers, then push those changes up and you should be good to go.
<img width="1399" alt="Screen Shot 2021-11-25 at 2 58 35 PM" src="https://user-images.githubusercontent.com/74033573/143496081-7757e6fa-29ee-4bd7-8869-96a94f9417a6.png">
<img width="1433" alt="Screen Shot 2021-11-25 at 2 58 52 PM" src="https://user-images.githubusercontent.com/74033573/143496082-526a175d-f553-4afb-a625-e55a7b580b50.png">

2021-11-30 15:22 UTC, cjmaret requested changes
getting better! just some style changes here for 768px, also, don't forget to add the dollar sign and triple 0's for the revenue

2021-11-30 15:22 UTC, cjmaret commented on frontend/src/components/startup-card/styledStartupCard.js
> +    margin-bottom: 20px;
isn't this 16px in 768px?

2021-11-30 15:22 UTC, cjmaret commented on frontend/src/components/startup-card/styledStartupCard.js
> +  @media (max-width: 770px) {
should be align-left i think

2021-11-30 15:22 UTC, cjmaret commented on frontend/src/components/startup-card/styledStartupCard.js
> +  @media (max-width: 770px) {
should be flex row, and flex-start i think? and the text should be flex-start too

2021-11-30 15:22 UTC, cjmaret commented on frontend/src/components/startup-card/styledStartupCard.js
>    flex-wrap: wrap;
almost perf, just should align the text and the two social media logos vertically to match each other, and probably put a space before the founder email

2021-11-30 15:22 UTC, cjmaret commented on frontend/src/components/startup-card/styledStartupCard.js
> +    padding: 20px 20px;
padding should be 44px 40px here

2021-11-30 15:22 UTC, cjmaret commented on frontend/src/components/startup-card/styledStartupCard.js
> +    margin-bottom: 20px;
shouldnt this stay 32px?

2021-11-30 15:22 UTC, cjmaret commented on frontend/src/components/startup-card/styledStartupCard.js
> +  @media (max-width: 770px) {
also needs a margin-bottom to separate it from the other cards

2021-12-06 01:38 UTC, McCambley requested changes
Hey Devin! Looks great! I'm going to request changes because of the needed change on the backend, but the other comments or changes can all be address after approval, or before, up to you. Nice job dude, looks great.

2021-12-06 01:38 UTC, McCambley commented on backend/server.js
> +const { MONGODB_URI, NODE_ENV} = process.env;
No need for NODE_ENV anymore

2021-12-06 01:38 UTC, McCambley commented on backend/server.js
> +mongoose.connect(NODE_ENV === 'production' ? MONGODB_URI: 'mongodb://localhost:27017/venturecat')
This should be removed and the above code should be uncommented

2021-12-06 01:38 UTC, McCambley commented on frontend/src/components/loading-startups-animation/styledLoadingStartupsAnimation.js
> +  background-color: #dadada;
Batmaaaaan!

2021-12-06 01:38 UTC, McCambley commented on frontend/src/components/startup-card/StartupCard.js
> +const date = moment(createdAt).format("Do MMMM, YYYY")
Whoooooa. Love it.

2021-12-06 01:38 UTC, McCambley commented on frontend/src/components/startup-card/StartupCard.js
>  function StartupCard({
It's beautiful! The card looks great on the personal startups page, but it doesn't seem to work right on the landing page. this might be a process of the responsiveness of the rest of the page, and perhaps will be remedied when the landing page responsiveness is done, but I'll mention it here and you can take a look and see what you think.

2021-12-06 03:13 UTC, McCambley approved these changes
Woo!

2021-12-06 15:35 UTC, cjmaret commented on frontend/src/components/startup-card/StartupCard.js
> +const date = moment(createdAt).format("Do MMMM, YYYY")
marvelous! looks awesome

2021-12-06 15:38 UTC, cjmaret commented on frontend/src/components/startup-card/StartupCard.js
> +        <ProfileImage src={logo} />
Profile Image's width is too small on all resolutions above 480px. The profile circle should be a circle, but it's too tall and not wide enough

2021-12-06 16:13 UTC, mentalcaries commented on frontend/src/components/startup-card/StartupCard.js
> +        <ProfileImage src={logo} />
I just added an actual jpg, but I can't reproduce the issue

2021-12-06 17:17 UTC, cjmaret approved these changes

2021-12-07 00:01 UTC, merged